# generated by chat.deepseek.com
import os
import json


def generate_libraries_json(root_dir):
    result = {}

    # 基础URL部分
    global_base_url = "https://cdn.stevesuk.eu.org/libraries/"
    cn_base_url = "http://47.108.78.18:12337/at-cdn/libraries/"

    for root, dirs, files in os.walk(root_dir):
        for file in files:
            if file.lower().endswith('.jar'):
                # 获取相对路径（相对于root_dir）
                rel_path = os.path.relpath(root, root_dir)

                # 处理根目录的特殊情况
                if rel_path == '.':
                    rel_path = ''

                # 转换路径分隔符为/
                formatted_rel_path = rel_path.replace('\\', '/')

                # 构建安装路径
                installed_path = f"/game/.minecraft/libraries/{formatted_rel_path}/{file}" if formatted_rel_path else f"/game/.minecraft/libraries/{file}"
                installed_path = installed_path.replace('//', '/')  # 处理空路径情况

                # 构建URL路径部分
                url_path = f"{formatted_rel_path}/" if formatted_rel_path else ""

                # 创建条目
                entry = {
                    "name": file,
                    "installed": installed_path,
                    "original": installed_path,
                    "global": {
                        "version": "1.0",
                        "type": "single",
                        "url": f"{global_base_url}{url_path}",
                        "path": file
                    },
                    "CN": {
                        "version": "1.0",
                        "type": "single",
                        "url": f"{cn_base_url}{url_path}",
                        "path": file
                    }
                }

                # 添加到结果字典
                result[file] = entry

    return json.dumps(result, indent=4, ensure_ascii=False)


# 使用示例
if __name__ == "__main__":
    libraries_path = input("请输入libraries文件夹路径：").strip()
    print("\n生成的JSON：\n")
    print(generate_libraries_json(libraries_path))